name: ip_tv_playlist
description: A server app using the shelf package and Docker.
version: 1.0.0
homepage: https://github.com/Relz/IP-TV-Playlist

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  args: 2.3.0
  shelf: 1.3.0
  shelf_router: 1.1.2
  postgres: 2.4.3
  pool: 1.5.0

dev_dependencies:
  lints: 2.0.0
